/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "DATABASE_URL_DEVELOPER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_URL_PRODUCTION": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyConnectionTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MySocket": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}